name: Improv Weekends
favicon: null
layout_spectrum: 0.6922988663427532
typography_spectrum: 0.11161101516336203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.388651697197929
  lightness: 0.23438289971090853
  saturation: 0.888180616311729
  rhythmicContrast: 0.7395561744924635
purpose: []
