name: Improv Weekends
favicon: null
layout_spectrum: 0.6922988663427532
typography_spectrum: 0.11161101516336203
title: UK Improv Weekends and Events
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#78aadc'
    - '#030200'
    - '#ffffff'
    - '#939146'
    - '#6a4f45'
  brandStrength: 0.388651697197929
  lightness: 0.23438289971090853
  saturation: 0.888180616311729
  rhythmicContrast: 0.7395561744924635
purpose: []
